service: burger-kitchen

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 20
  environment:
    TABLE_ORDERS: ${env:TABLE_PEDIDOS}
    TABLE_HISTORIAL_ESTADOS: ${env:TABLE_HISTORIAL_ESTADOS}
    TABLE_PRODUCTS: ${env:TABLE_PRODUCTOS}
  iam:
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/LabRole


custom:
  pythonRequirements:
    fileName: ../requirements.txt

functions:
  validateStock:
    handler: validate_stock.validate_stock
    description: Valida disponibilidad de stock de productos
  
  listKitchenPending:
    handler: list.list_pending
    events:
      - http:
          path: cocina/pendientes
          method: get
          cors: true
  
  listKitchenCooking:
    handler: list.list_cooking
    events:
      - http:
          path: cocina/en-curso
          method: get
          cors: true

  confirmKitchen:
    handler: confirm.confirm
    events:
      - http:
          path: cocina/confirmar
          method: post
          cors: true

  completeCooking:
    handler: complete.complete
    events:
      - http:
          path: cocina/terminar
          method: post
          cors: true

resources:
  Outputs:
    ValidateStockLambdaArn:
      Value: !GetAtt ValidateStockLambdaFunction.Arn
      Export:
        Name: ValidateStockLambdaArn-${sls:stage}


