service: burger-order

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 20
  environment:
    TABLE_ORDERS: ${env:TABLE_PEDIDOS}
    TABLE_USERS: ${env:TABLE_USUARIOS}
    TABLE_PRODUCTS: ${env:TABLE_PRODUCTOS}
    TABLE_HISTORIAL_ESTADOS: ${env:TABLE_HISTORIAL_ESTADOS}
    STATE_MACHINE_ARN: arn:aws:states:${aws:region}:${aws:accountId}:stateMachine:BurgerFlow-${sls:stage}
    VALIDAR_TOKEN_LAMBDA_NAME: burger-auth-${sls:stage}-auth
  iam:
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/LabRole


custom:
  pythonRequirements:
    fileName: ../requirements.txt

functions:
  createOrder:
    handler: create.create_order
    events:
      - http:
          path: pedido
          method: post
          authorizer: 
             type: TOKEN
             arn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:burger-auth-${sls:stage}-auth
          cors: true

  listMyOrders:
    handler: handlers/list_my_orders.handler
    events:
      - http:
          path: pedidos/mis-pedidos
          method: get
          authorizer: 
             type: TOKEN
             arn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:burger-auth-${sls:stage}-auth
          cors: true

  listAllOrders:
    handler: handlers/list_all_orders.handler
    events:
      - http:
          path: pedidos/todos
          method: get
          authorizer: 
             type: TOKEN
             arn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:burger-auth-${sls:stage}-auth
          cors: true

  checkStatus:
    handler: handlers/get_status.handler
    events:
      - http:
          path: pedido/status
          method: get
          cors: true

  orderHistory:
    handler: handlers/list_my_orders.handler # Reusing listMyOrders as per requirement
    events:
      - http:
          path: pedido/historial
          method: get
          authorizer: 
             type: TOKEN
             arn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:burger-auth-${sls:stage}-auth
          cors: true
