service: burger-order

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 20
  environment:
    TABLE_ORDERS: ${env:TABLE_PEDIDOS}
    TABLE_USERS: ${env:TABLE_USUARIOS}
    TABLE_PRODUCTS: ${env:TABLE_PRODUCTOS}
    TABLE_HISTORIAL_ESTADOS: ${env:TABLE_HISTORIAL_ESTADOS}
    STATE_MACHINE_ARN: ${env:STATE_MACHINE_ARN}
    VALIDAR_TOKEN_LAMBDA_NAME: burger-auth-${sls:stage}-auth
  iam:
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/LabRole


custom:
  pythonRequirements:
    fileName: ../requirements.txt

functions:
  createOrder:
    handler: create.create_order
    events:
      - http:
          path: pedido
          method: post
          authorizer: 
             type: TOKEN
             arn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:burger-auth-${sls:stage}-auth
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

  listMyOrders:
    handler: list_my_orders.handler
    events:
      - http:
          path: pedidos/mis-pedidos
          method: get
          authorizer: 
             type: TOKEN
             arn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:burger-auth-${sls:stage}-auth
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

  listAllOrders:
    handler: list_all_orders.handler
    events:
      - http:
          path: pedidos/todos
          method: get
          authorizer: 
             type: TOKEN
             arn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:burger-auth-${sls:stage}-auth
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

  checkStatus:
    handler: get_status.handler
    events:
      - http:
          path: pedido/status
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

  orderHistory:
    handler: list_my_orders.handler # Reusing listMyOrders as per requirement
    events:
      - http:
          path: pedido/historial
          method: get
          authorizer: 
             type: TOKEN
             arn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:burger-auth-${sls:stage}-auth
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

resources:
  Resources:
    # Add Gateway Response for Unauthorized errors to include CORS headers
    GatewayResponseUnauthorized:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    
    # Add Gateway Response for Access Denied errors to include CORS headers
    GatewayResponseAccessDenied:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
        ResponseType: ACCESS_DENIED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '403'
