service: burger-order

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 20
  environment:
    TABLE_ORDERS: ${env:TABLE_PEDIDOS}
    TABLE_USERS: ${env:TABLE_USUARIOS}
    TABLE_PRODUCTS: ${env:TABLE_PRODUCTOS}
    TABLE_HISTORIAL_ESTADOS: ${env:TABLE_HISTORIAL_ESTADOS}
    STATE_MACHINE_ARN: arn:aws:states:${aws:region}:${aws:accountId}:stateMachine:BurgerFlow-${sls:stage}
  iam:
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/LabRole


custom:
  pythonRequirements:
    fileName: ../requirements.txt

functions:
  createOrder:
    handler: create.create_order
    events:
      - http:
          path: pedido
          method: post
          authorizer: 
             type: TOKEN
             # Usar ARN de la funci√≥n auth directamente
             arn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:burger-auth-${sls:stage}-auth
          cors: true

