service: burger-auth

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 20
  environment:
    TABLE_USERS: ${env:TABLE_USUARIOS}
    TOKENS_TABLE_USERS: ${env:TABLE_TOKENS_USUARIOS}
    TABLE_EMPLEADOS: ${env:TABLE_EMPLEADOS}
    TABLE_ORDERS: ${env:TABLE_PEDIDOS}
  iam:
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/LabRole

custom:
  pythonRequirements:
    fileName: ../requirements.txt

functions:
  auth:
    handler: authorize.authorize
  
  register:
    handler: register.register_user
    events:
      - http:
          path: register
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
  
  login:
    handler: login.login
    events:
      - http:
          path: login
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

  loginEmpleado:
    handler: login_empleado.login_empleado
    events:
      - http:
          path: login/empleado
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
  
  registerToken:
    handler: register_token.register_token
    description: Registra task tokens para Step Functions

resources:
  Outputs:
    RegisterTokenLambdaArn:
      Value: !GetAtt RegisterTokenLambdaFunction.Arn
      Export:
        Name: RegisterTokenLambdaArn-${sls:stage}


